# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43b87bbf449851435bd8ff5c27bfb9f200e428cca7807c91caf300ac5e82dc40fd798de8e036d5984291ab5283153e7982c2c07bb34be9a1050802178b554a9f

test:
  secret_key_base: 564bb7765b907164c97527549361ddf5985b3ad3e99edbf03bdc7261197d55010eed989ca21b0ebad056d97e830f20f28908a5a02316b87b432590e42889b0b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
